[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "bookmarks"
version = "1.0.0"
dependencies = [
    "starlette",
    "uvicorn",
    "asyncpg",
    "pydantic",
    "python-dotenv",
    "SQLAlchemy",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I"]
