CREATE TABLE BOOKMARKS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    TITLE TEXT NOT NULL,
    PAGE INT NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
);
