DROP TABLE IF EXISTS BOOKMARKS;

CREATE TABLE BOOKMARKS (
    BM_SEQ INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE TEXT NOT NULL,
    AUTHOR TEXT NOT NULL,
    PAGE INT NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);



-- CREATE BOOKMARKS (
--     BM_UUID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     BM_SEQ INT GENERATED ALWAYS AS IDENTITY,
--     TITLE TEXT NOT NULL,
--     PAGE INT NOT NULL,
--     CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
--     UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
-- );

-- CREATE TRIGGER for updated at
-- attempty uuid?
